import re
from decimal import Decimal
from typing import Any, Dict, Optional


class GSTNAdapter:
    """Simulated adapter for GSTN e-Invoice IRP (Invoice Registration Portal) and GSTIN checks."""

    STANDARD_HSN_RATES = {
        "7307": Decimal("18.0"),  # Tube or pipe fittings (flanges)
        "7307.29": Decimal("18.0"),
        "8481": Decimal("18.0"),  # Valves and pipe fittings
        "8481.80": Decimal("18.0"),
        "8501": Decimal("18.0"),  # Electric motors & generators
        "8413": Decimal("18.0"),  # Pumps for liquids
        "7208": Decimal("18.0"),  # Flat-rolled products of iron/steel
    }

    @staticmethod
    async def verify_irn(irn: Optional[str]) -> Dict[str, Any]:
        """Validates 64-character hash Invoice Reference Number generated by IRP."""
        if not irn:
            return {
                "valid": False,
                "error": "IRN is missing",
                "status": "NOT_FOUND",
                "signed_qr_present": False,
            }

        irn_clean = irn.strip().lower()
        is_hex_64 = bool(re.match(r"^[0-9a-f]{64}$", irn_clean))

        if not is_hex_64:
            return {
                "valid": False,
                "error": "Invalid IRN hash structure. Must be exactly 64 hexadecimal characters.",
                "status": "MALFORMED_HASH",
                "signed_qr_present": False,
            }

        return {
            "valid": True,
            "status": "ACTIVE_REGISTERED",
            "irn": irn_clean,
            "signed_qr_present": True,
            "ack_no": "112610984421",
            "ack_date": "2026-03-01T10:15:30Z",
        }

    @staticmethod
    def validate_gstin(gstin: Optional[str]) -> Dict[str, Any]:
        """Validates Indian 15-character Goods and Services Tax Identification Number."""
        if not gstin:
            return {"valid": False, "reason": "GSTIN is missing"}

        clean = gstin.strip().upper()
        # Structure: 2-digit state code + 10-char PAN + 1-digit entity count + 'Z' + 1-char checksum
        pattern = r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$"
        if not re.match(pattern, clean):
            return {
                "valid": False,
                "reason": f"GSTIN '{clean}' does not match standard 15-character GSTIN format.",
            }

        state_code = clean[:2]
        pan = clean[2:12]
        return {
            "valid": True,
            "gstin": clean,
            "state_code": state_code,
            "pan": pan,
            "status": "ACTIVE",
        }

    @classmethod
    def verify_hsn_rate(cls, hsn_code: Optional[str], billed_gst_rate: Decimal) -> Dict[str, Any]:
        """Validates statutory GST rate against declared HSN code."""
        if not hsn_code:
            return {"match": True, "note": "No HSN declared"}

        prefix4 = hsn_code.strip()[:4]
        expected_rate = cls.STANDARD_HSN_RATES.get(prefix4, Decimal("18.0"))

        diff = abs(expected_rate - billed_gst_rate)
        if diff > Decimal("0.01"):
            return {
                "match": False,
                "hsn": hsn_code,
                "expected_rate": expected_rate,
                "billed_rate": billed_gst_rate,
                "error": f"Statutory GST rate for HSN {hsn_code} is {expected_rate}%, but invoice billed {billed_gst_rate}%.",
            }

        return {
            "match": True,
            "hsn": hsn_code,
            "rate": expected_rate,
        }


gstn = GSTNAdapter()
